package GUI;


import java.awt.Desktop;
import java.awt.event.ActionListener;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import java.util.logging.Level;
import java.util.logging.Logger;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Emil
 */
public class Menu extends javax.swing.JPanel {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        informationBtn = new javax.swing.JButton();
        QuizBtn = new javax.swing.JButton();
        informationOnSightBtn = new javax.swing.JButton();
        languageBtn = new javax.swing.JButton();
        MenuBtn = new javax.swing.JButton();

        informationBtn.setText("Information");
        informationBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        informationBtn.setMaximumSize(new java.awt.Dimension(180, 70));
        informationBtn.setMinimumSize(new java.awt.Dimension(180, 70));
        informationBtn.setPreferredSize(new java.awt.Dimension(180, 70));
        informationBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                informationBtnActionPerformed(evt);
            }
        });

        QuizBtn.setText("Quiz");
        QuizBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        QuizBtn.setMaximumSize(new java.awt.Dimension(180, 70));
        QuizBtn.setMinimumSize(new java.awt.Dimension(180, 70));
        QuizBtn.setPreferredSize(new java.awt.Dimension(180, 70));
        QuizBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QuizBtnActionPerformed(evt);
            }
        });

        informationOnSightBtn.setText("Information On Sights");
        informationOnSightBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        informationOnSightBtn.setMaximumSize(new java.awt.Dimension(180, 70));
        informationOnSightBtn.setMinimumSize(new java.awt.Dimension(180, 70));
        informationOnSightBtn.setPreferredSize(new java.awt.Dimension(180, 70));
        informationOnSightBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                informationOnSightBtnActionPerformed(evt);
            }
        });

        languageBtn.setText("Change Language");
        languageBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        languageBtn.setMaximumSize(new java.awt.Dimension(180, 70));
        languageBtn.setMinimumSize(new java.awt.Dimension(180, 70));
        languageBtn.setPreferredSize(new java.awt.Dimension(180, 70));
        languageBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                languageBtnActionPerformed(evt);
            }
        });

        MenuBtn.setText("Menu");
        MenuBtn.setMaximumSize(new java.awt.Dimension(180, 70));
        MenuBtn.setMinimumSize(new java.awt.Dimension(180, 70));
        MenuBtn.setPreferredSize(new java.awt.Dimension(180, 70));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(MenuBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(informationBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(informationOnSightBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(QuizBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(languageBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(260, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(MenuBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(informationBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(informationOnSightBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(QuizBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(languageBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(295, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void informationBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_informationBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_informationBtnActionPerformed

    private void QuizBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QuizBtnActionPerformed

    }//GEN-LAST:event_QuizBtnActionPerformed

    private void languageBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_languageBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_languageBtnActionPerformed

    private void informationOnSightBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_informationOnSightBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_informationOnSightBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton MenuBtn;
    private javax.swing.JButton QuizBtn;
    private javax.swing.JButton informationBtn;
    private javax.swing.JButton informationOnSightBtn;
    private javax.swing.JButton languageBtn;
    // End of variables declaration//GEN-END:variables

    public void addActionListenerWelcomeScreen(ActionListener l){
        MenuBtn.addActionListener(l);
    }
    
    public void addActionListenerInformationScreen(ActionListener l){
        informationBtn.addActionListener(l);
    }
    
    public void addActionListenerChangeLanguage(ActionListener l){
        languageBtn.addActionListener(l);
    }
    
    public void addActionListenerInformationOnSights(ActionListener l){
        informationOnSightBtn.addActionListener(l);
    }

}
