/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.Submenu;

import java.awt.event.ActionListener;

/**
 *
 * @author ejer
 */
public class InformationOnSights extends javax.swing.JPanel {

    /**
     * Creates new form InformationOnSights
     */
    public InformationOnSights() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        TheOperaBtn = new javax.swing.JButton();
        TheLittleMermaidBtn = new javax.swing.JButton();
        TrekronerFortressBtn = new javax.swing.JButton();
        TheOldStockExchangeBtn = new javax.swing.JButton();
        TheBlackDiamondBtn = new javax.swing.JButton();
        ChristiansborgPalaceBtn = new javax.swing.JButton();
        KastelletBtn = new javax.swing.JButton();
        OurSavioursChurchBtn = new javax.swing.JButton();

        jButton1.setText("Back");
        jButton1.setMaximumSize(new java.awt.Dimension(180, 70));
        jButton1.setMinimumSize(new java.awt.Dimension(180, 70));
        jButton1.setPreferredSize(new java.awt.Dimension(180, 70));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        TheOperaBtn.setText("The Royal Opera House");
        TheOperaBtn.setMaximumSize(new java.awt.Dimension(180, 70));
        TheOperaBtn.setMinimumSize(new java.awt.Dimension(180, 70));
        TheOperaBtn.setPreferredSize(new java.awt.Dimension(180, 70));
        TheOperaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TheOperaBtnActionPerformed(evt);
            }
        });

        TheLittleMermaidBtn.setText("The Little Mermaid");
        TheLittleMermaidBtn.setMaximumSize(new java.awt.Dimension(180, 70));
        TheLittleMermaidBtn.setMinimumSize(new java.awt.Dimension(180, 70));
        TheLittleMermaidBtn.setPreferredSize(new java.awt.Dimension(180, 70));
        TheLittleMermaidBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TheLittleMermaidBtnActionPerformed(evt);
            }
        });

        TrekronerFortressBtn.setText("Trekroner Fortress");
        TrekronerFortressBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TrekronerFortressBtnActionPerformed(evt);
            }
        });

        TheOldStockExchangeBtn.setText("The Old Stock Exchange");
        TheOldStockExchangeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TheOldStockExchangeBtnActionPerformed(evt);
            }
        });

        TheBlackDiamondBtn.setText("The Black Diamond");
        TheBlackDiamondBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TheBlackDiamondBtnActionPerformed(evt);
            }
        });

        ChristiansborgPalaceBtn.setText("Christiansborg Palace");

        KastelletBtn.setText("Kastellet");

        OurSavioursChurchBtn.setText("Our Saviour´s Church ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(OurSavioursChurchBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(KastelletBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ChristiansborgPalaceBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(TheBlackDiamondBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(TrekronerFortressBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(TheOperaBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(TheLittleMermaidBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(TheOldStockExchangeBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(260, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TheOperaBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TheLittleMermaidBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TrekronerFortressBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TheOldStockExchangeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TheBlackDiamondBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ChristiansborgPalaceBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(KastelletBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(OurSavioursChurchBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(185, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void TheOperaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TheOperaBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TheOperaBtnActionPerformed

    private void TheLittleMermaidBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TheLittleMermaidBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TheLittleMermaidBtnActionPerformed

    private void TrekronerFortressBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TrekronerFortressBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TrekronerFortressBtnActionPerformed

    private void TheOldStockExchangeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TheOldStockExchangeBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TheOldStockExchangeBtnActionPerformed

    private void TheBlackDiamondBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TheBlackDiamondBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TheBlackDiamondBtnActionPerformed

    public void addActionListenerMenu(ActionListener l) {
        jButton1.addActionListener(l);
    }
    
    public void addActionListenerTheOpera(ActionListener l) {
        TheOperaBtn.addActionListener(l);
    }
    
    public void addActionListenerTheLittleMermaid(ActionListener l) {
        TheLittleMermaidBtn.addActionListener(l);
    }
    
    public void addActionListenerTrekronerFortress(ActionListener l) {
        TrekronerFortressBtn.addActionListener(l);
    }
    public void addActionListenerTheOldStockExchange(ActionListener l) {
        TheOldStockExchangeBtn.addActionListener(l);
    }
    public void addActionListenerKastellet(ActionListener l) {
        KastelletBtn.addActionListener(l);
    }
    public void addActionListenerChristiansborgPalace(ActionListener l) {
        ChristiansborgPalaceBtn.addActionListener(l);
    }
    public void addActionListenerOurSaviorsChurch(ActionListener l) {
        OurSavioursChurchBtn.addActionListener(l);
    }
    public void addActionListenerTheBlackDiamond(ActionListener l) {
        TheBlackDiamondBtn.addActionListener(l);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ChristiansborgPalaceBtn;
    private javax.swing.JButton KastelletBtn;
    private javax.swing.JButton OurSavioursChurchBtn;
    private javax.swing.JButton TheBlackDiamondBtn;
    private javax.swing.JButton TheLittleMermaidBtn;
    private javax.swing.JButton TheOldStockExchangeBtn;
    private javax.swing.JButton TheOperaBtn;
    private javax.swing.JButton TrekronerFortressBtn;
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables
}
